services:
  # Backend Java Service
  - type: web
    name: banking-api
    runtime: image
    repo: https://github.com/MostafizFahim/banking-microservices
    plan: free
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod