# Kept as-is for local development
spring.datasource.url=jdbc:h2:mem:bankingdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

server.port=8081
spring.application.name=account-service

logging.level.com.banking.account=DEBUG

# Default for local development
admin.secret.key=SUPER_SECRET_KEY_123
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.cors.allowed-origins=http://localhost:4200,http://127.0.0.1:4200
